name: Hello GitHub Actions
on: [push]

env:
  COURSE: CloudComputing
jobs:
  greet:
    runs-on: ubuntu-latest
    steps:
      - name: Say Hello
        run: echo "Hello from GitHub Actions! (${COURSE})"
      - name: Notification
        run: echo "I'll list files."
      - run: ls -al
