name: Hello GitHub Actions
on: [push]

jobs:
  greet:
    runs-on: ubuntu-latest
    env:
      COURSE: CloudComputing
    steps:
      - uses: actions/checkout@v4
      - name: Say Hello
        run: echo "Hello from GitHub Actions! (${COURSE})"
      - name: Notification
        run: echo "I'll list files."
      - run: ls -al
  goodbye:
    needs: greet
    runs-on: ubuntu-latest
    steps:
      - run: echo "Goodbye (${COURSE})"
      - run: ls -al
      - run: echo "${{ secrets.MY_SECRET }}"
